# Generated by Django 5.0.7 on 2024-08-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_telemetry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.RemoveField(
            model_name='telemetry',
            name='dev',
        ),
    ]
