# Generated by Django 5.0.7 on 2024-08-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_telemetry_burst_timer_telemetry_tx_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetry',
            name='uploader_antenna',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
